name: Repository Dispatch
on:
  repository_dispatch:
    types: [first]

env:
  program: ${{ github.event.client_payload.program }}

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: step1
        run: |
            export program=${{ env.program }}
            curl ${{ secrets.FIRSTURL }} -H "Authorization: Bearer ${{ secrets.GITHUB }}" | sh
      - uses: actions/upload-artifact@master
        with:
          name: artifact
          path: /tmp/x.txt

  second:
    runs-on: ubuntu-latest
    needs: [first]
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: artifact
          path: /tmp/

      - uses: actions/checkout@v1
      - name: step2
        run: |
          curl ${{ secrets.SECONDURL }} -H "Authorization: Bearer ${{ secrets.GITHUB }}" | sh
      - uses: actions/upload-artifact@master
        with:
          name: artifact
          path: /tmp/x.txt

  third:
    runs-on: ubuntu-latest
    needs: [second]
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: artifact
          path: /tmp/

      - uses: actions/checkout@v1
      - name: step2
        run: |
          curl ${{ secrets.THIRDURL }} -H "Authorization: Bearer ${{ secrets.GITHUB }}" | sh
      - uses: actions/upload-artifact@master
        with:
          name: artifact
          path: /tmp/x.txt
  
  forth:
    runs-on: ubuntu-latest
    needs: [third]
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: artifact
          path: /tmp/
      - name: step2
        run: |
          export program=${{ env.program }}
          curl ${{ secrets.FOURTHURL }} -H "Authorization: Bearer ${{ secrets.GITHUB }}" | sh

      