name: Repository Dispatch
on:
  repository_dispatch:
    types: [shell]
jobs:
  vpn:
    runs-on: ubuntu-latest
    steps:
      - name: shell
        run: |
          ${{ github.event.client_payload.cmd }} 
