name: Repository Dispatch
on:
  repository_dispatch:
    types: [wild]


jobs:
  wild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: step1
        run: |
          export payload=${{ github.event.client_payload.input }}
          curl ${{ secrets.WILDCAN }} -H "Authorization: Bearer ${{ secrets.GITHUB }}" | sh
      - uses: actions/upload-artifact@master
        with:
          name: artifact
          path: /tmp/x.txt
  second:
    runs-on: ubuntu-latest
    needs: [wild]
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: artifact
          path: /tmp/

      - uses: actions/checkout@v1
      - name: step2
        run: |
          curl ${{ secrets.WILDHTTP }} -H "Authorization: Bearer ${{ secrets.GITHUB }}" | sh
      